In [2]:

import pandas as pd

data = pd.read_csv('weatherAUS.csv')

In [3]:
data

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W           44.0          W  ...        71.0   
1            NaN         WNW           44.0        NNW  ...        44.0   
2            NaN         WSW           46.0          W  ...        38.0   
3            NaN          NE           24.0         SE  ...        45.0   
4            NaN           W           41.0        ENE  ...        82.0   
...          ...         ...            ...        ...  ...         ...   
145455       NaN           E           31.0         SE  ...        51.0   
145456       NaN         NNW           22.0         SE  ...        56.0   
145457       NaN           N           37.0         SE  ...        53.0   
145458       NaN          SE           28.0        SSE  ...        51.0   
145459       NaN         NaN            NaN        ESE  ...        62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8         No            No  
1          24.3         No            No  
2          23.2         No            No  
3          26.5         No            No  
4          29.7         No            No  
...         ...        ...           ...  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  
145459     20.9         No           NaN  

[145460 rows x 23 columns]

In [4]:
print(data)

              Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W           44.0          W  ... 

In [5]:
data.shape

(145460, 23)

In [6]:
data.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [7]:
data.tail()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
145455       NaN           E           31.0         SE  ...        51.0   
145456       NaN         NNW           22.0         SE  ...        56.0   
145457       NaN           N           37.0         SE  ...        53.0   
145458       NaN          SE           28.0        SSE  ...        51.0   
145459       NaN         NaN            NaN        ESE  ...        62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  
145459     20.9         No           NaN  

[5 rows x 23 columns]

In [8]:
data.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000   
mean       12.194034      23.221348       2.360918      5.468232   
std         6.398495       7.119049       8.478060      4.193704   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.900000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000   
mean       7.611178      40.035230      14.043426      18.662657   
std        3.785483      13.607062       8.915375       8.809800   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.800000      31.000000       7.000000      13.000000   
50%        8.400000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000   
mean       68.880831      51.539116    1017.64994    1015.255889   
std        19.029164      20.795902       7.10653       7.037414   
min         0.000000       0.000000     980.50000     977.100000   
25%        57.000000      37.000000    1012.90000    1010.400000   
50%        70.000000      52.000000    1017.60000    1015.200000   
75%        83.000000      66.000000    1022.40000    1020.000000   
max       100.000000     100.000000    1041.00000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am       Temp3pm  
count  89572.000000  86102.000000  143693.000000  141851.00000  
mean       4.447461      4.509930      16.990631      21.68339  
std        2.887159      2.720357       6.488753       6.93665  
min        0.000000      0.000000      -7.200000      -5.40000  
25%        1.000000      2.000000      12.300000      16.60000  
50%        5.000000      5.000000      16.700000      21.10000  
75%        7.000000      7.000000      21.600000      26.40000  
max        9.000000      9.000000      40.200000      46.70000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           145460 non-null  object 
 1   Location       145460 non-null  object 
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object 
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object 
 10  WindDir3pm     141232 non-null  object 
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null

In [10]:
data.isnull()

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0       False     False    False    False     False         True      True   
1       False     False    False    False     False         True      True   
2       False     False    False    False     False         True      True   
3       False     False    False    False     False         True      True   
4       False     False    False    False     False         True      True   
...       ...       ...      ...      ...       ...          ...       ...   
145455  False     False    False    False     False         True      True   
145456  False     False    False    False     False         True      True   
145457  False     False    False    False     False         True      True   
145458  False     False    False    False     False         True      True   
145459  False     False    False     True     False         True      True   

        WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity9am  Humidity3pm  \
0             False          False       False  ...        False        False   
1             False          False       False  ...        False        False   
2             False          False       False  ...        False        False   
3             False          False       False  ...        False        False   
4             False          False       False  ...        False        False   
...             ...            ...         ...  ...          ...          ...   
145455        False          False       False  ...        False        False   
145456        False          False       False  ...        False        False   
145457        False          False       False  ...        False        False   
145458        False          False       False  ...        False        False   
145459         True           True       False  ...        False        False   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0             False        False     False      True    False    False   
1             False        False      True      True    False    False   
2             False        False      True     False    False    False   
3             False        False      True      True    False    False   
4             False        False     False     False    False    False   
...             ...          ...       ...       ...      ...      ...   
145455        False        False      True      True    False    False   
145456        False        False      True      True    False    False   
145457        False        False      True      True    False    False   
145458        False        False     False     False    False    False   
145459        False        False     False     False    False    False   

        RainToday  RainTomorrow  
0           False         False  
1           False         False  
2           False         False  
3           False         False  
4           False         False  
...           ...           ...  
145455      False         False  
145456      False         False  
145457      False         False  
145458      False         False  
145459      False          True  

[145460 rows x 23 columns]

In [11]:
data.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [12]:
data = data.dropna(how='any')

In [13]:
data.isnull()

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
6049    False     False    False    False     False        False     False   
6050    False     False    False    False     False        False     False   
6052    False     False    False    False     False        False     False   
6053    False     False    False    False     False        False     False   
6054    False     False    False    False     False        False     False   
...       ...       ...      ...      ...       ...          ...       ...   
142298  False     False    False    False     False        False     False   
142299  False     False    False    False     False        False     False   
142300  False     False    False    False     False        False     False   
142301  False     False    False    False     False        False     False   
142302  False     False    False    False     False        False     False   

        WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity9am  Humidity3pm  \
6049          False          False       False  ...        False        False   
6050          False          False       False  ...        False        False   
6052          False          False       False  ...        False        False   
6053          False          False       False  ...        False        False   
6054          False          False       False  ...        False        False   
...             ...            ...         ...  ...          ...          ...   
142298        False          False       False  ...        False        False   
142299        False          False       False  ...        False        False   
142300        False          False       False  ...        False        False   
142301        False          False       False  ...        False        False   
142302        False          False       False  ...        False        False   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
6049          False        False     False     False    False    False   
6050          False        False     False     False    False    False   
6052          False        False     False     False    False    False   
6053          False        False     False     False    False    False   
6054          False        False     False     False    False    False   
...             ...          ...       ...       ...      ...      ...   
142298        False        False     False     False    False    False   
142299        False        False     False     False    False    False   
142300        False        False     False     False    False    False   
142301        False        False     False     False    False    False   
142302        False        False     False     False    False    False   

        RainToday  RainTomorrow  
6049        False         False  
6050        False         False  
6052        False         False  
6053        False         False  
6054        False         False  
...           ...           ...  
142298      False         False  
142299      False         False  
142300      False         False  
142301      False         False  
142302      False         False  

[56420 rows x 23 columns]

In [14]:
data.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           56420 non-null  object 
 1   Location       56420 non-null  object 
 2   MinTemp        56420 non-null  float64
 3   MaxTemp        56420 non-null  float64
 4   Rainfall       56420 non-null  float64
 5   Evaporation    56420 non-null  float64
 6   Sunshine       56420 non-null  float64
 7   WindGustDir    56420 non-null  object 
 8   WindGustSpeed  56420 non-null  float64
 9   WindDir9am     56420 non-null  object 
 10  WindDir3pm     56420 non-null  object 
 11  WindSpeed9am   56420 non-null  float64
 12  WindSpeed3pm   56420 non-null  float64
 13  Humidity9am    56420 non-null  float64
 14  Humidity3pm    56420 non-null  float64
 15  Pressure9am    56420 non-null  float64
 16  Pressure3pm    56420 non-null  float64
 17  Cloud9am       56420 non-null  float64
 18  Cloud3p

In [16]:
data.describe()

MinTemp       MaxTemp      Rainfall   Evaporation      Sunshine  \
count  56420.000000  56420.000000  56420.000000  56420.000000  56420.000000   
mean      13.464770     24.219206      2.130397      5.503135      7.735626   
std        6.416689      6.970676      7.014822      3.696282      3.758153   
min       -6.700000      4.100000      0.000000      0.000000      0.000000   
25%        8.600000     18.700000      0.000000      2.800000      5.000000   
50%       13.200000     23.900000      0.000000      5.000000      8.600000   
75%       18.400000     29.700000      0.600000      7.400000     10.700000   
max       31.400000     48.100000    206.200000     81.200000     14.500000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm   Humidity9am   Humidity3pm  \
count   56420.000000  56420.000000  56420.000000  56420.000000  56420.000000   
mean       40.877366     15.667228     19.786778     65.874123     49.601985   
std        13.335232      8.317005      8.510180     18.513289     20.197040   
min         9.000000      2.000000      2.000000      0.000000      0.000000   
25%        31.000000      9.000000     13.000000     55.000000     35.000000   
50%        39.000000     15.000000     19.000000     67.000000     50.000000   
75%        48.000000     20.000000     26.000000     79.000000     63.000000   
max       124.000000     67.000000     76.000000    100.000000    100.000000   

        Pressure9am   Pressure3pm      Cloud9am      Cloud3pm       Temp9am  \
count  56420.000000  56420.000000  56420.000000  56420.000000  56420.000000   
mean    1017.239505   1014.795580      4.241705      4.326515     18.204961   
std        6.909357      6.870892      2.797162      2.647251      6.567991   
min      980.500000    977.100000      0.000000      0.000000     -0.700000   
25%     1012.700000   1010.100000      1.000000      2.000000     13.100000   
50%     1017.200000   1014.700000      5.000000      5.000000     17.800000   
75%     1021.800000   1019.400000      7.000000      7.000000     23.300000   
max     1040.400000   1038.900000      8.000000      9.000000     39.400000   

            Temp3pm  
count  56420.000000  
mean      22.710333  
std        6.836543  
min        3.700000  
25%       17.400000  
50%       22.400000  
75%       27.900000  
max       46.100000

In [17]:
data.shape

(56420, 23)

In [18]:
data

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
6049    2009-01-01    Cobar     17.9     35.2       0.0         12.0   
6050    2009-01-02    Cobar     18.4     28.9       0.0         14.8   
6052    2009-01-04    Cobar     19.4     37.6       0.0         10.8   
6053    2009-01-05    Cobar     21.9     38.4       0.0         11.4   
6054    2009-01-06    Cobar     24.2     41.0       0.0         11.2   
...            ...      ...      ...      ...       ...          ...   
142298  2017-06-20   Darwin     19.3     33.4       0.0          6.0   
142299  2017-06-21   Darwin     21.2     32.6       0.0          7.6   
142300  2017-06-22   Darwin     20.7     32.8       0.0          5.6   
142301  2017-06-23   Darwin     19.5     31.8       0.0          6.2   
142302  2017-06-24   Darwin     20.2     31.7       0.0          5.6   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
6049        12.3         SSW           48.0        ENE  ...        20.0   
6050        13.0           S           37.0        SSE  ...        30.0   
6052        10.6         NNE           46.0        NNE  ...        42.0   
6053        12.2         WNW           31.0        WNW  ...        37.0   
6054         8.4         WNW           35.0         NW  ...        19.0   
...          ...         ...            ...        ...  ...         ...   
142298      11.0         ENE           35.0         SE  ...        63.0   
142299       8.6           E           37.0         SE  ...        56.0   
142300      11.0           E           33.0          E  ...        46.0   
142301      10.6         ESE           26.0         SE  ...        62.0   
142302      10.7         ENE           30.0        ENE  ...        73.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
6049           13.0       1006.3       1004.4       2.0       5.0     26.6   
6050            8.0       1012.9       1012.1       1.0       1.0     20.3   
6052           22.0       1012.3       1009.2       1.0       6.0     28.7   
6053           22.0       1012.7       1009.1       1.0       5.0     29.1   
6054           15.0       1010.7       1007.4       1.0       6.0     33.6   
...             ...          ...          ...       ...       ...      ...   
142298         32.0       1013.9       1010.5       0.0       1.0     24.5   
142299         28.0       1014.6       1011.2       7.0       0.0     24.8   
142300         23.0       1015.3       1011.8       0.0       0.0     24.8   
142301         58.0       1014.9       1010.7       1.0       1.0     24.8   
142302         32.0       1013.9       1009.7       6.0       5.0     25.4   

        Temp3pm  RainToday  RainTomorrow  
6049       33.4         No            No  
6050       27.0         No            No  
6052       34.9         No            No  
6053       35.6         No            No  
6054       37.6         No            No  
...         ...        ...           ...  
142298     32.3         No            No  
142299     32.0         No            No  
142300     32.1         No            No  
142301     29.2         No            No  
142302     31.0         No            No  

[56420 rows x 23 columns]

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           56420 non-null  object 
 1   Location       56420 non-null  object 
 2   MinTemp        56420 non-null  float64
 3   MaxTemp        56420 non-null  float64
 4   Rainfall       56420 non-null  float64
 5   Evaporation    56420 non-null  float64
 6   Sunshine       56420 non-null  float64
 7   WindGustDir    56420 non-null  object 
 8   WindGustSpeed  56420 non-null  float64
 9   WindDir9am     56420 non-null  object 
 10  WindDir3pm     56420 non-null  object 
 11  WindSpeed9am   56420 non-null  float64
 12  WindSpeed3pm   56420 non-null  float64
 13  Humidity9am    56420 non-null  float64
 14  Humidity3pm    56420 non-null  float64
 15  Pressure9am    56420 non-null  float64
 16  Pressure3pm    56420 non-null  float64
 17  Cloud9am       56420 non-null  float64
 18  Cloud3p

In [20]:
import numpy as np

# Sample dataset
date = np.array(data['Date'])
date = [[int(part) for part in date[i].split('-')] for i in range(len( date ))]

date = np.array(date).T
date

array([[2009, 2009, 2009, ..., 2017, 2017, 2017],
       [   1,    1,    1, ...,    6,    6,    6],
       [   1,    2,    4, ...,   22,   23,   24]])

In [21]:
years = date[0]
years

array([2009, 2009, 2009, ..., 2017, 2017, 2017])

In [22]:
months = date[1]
months

array([1, 1, 1, ..., 6, 6, 6])

In [23]:
dates = date[2]
dates

array([ 1,  2,  4, ..., 22, 23, 24])

In [24]:
data

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
6049    2009-01-01    Cobar     17.9     35.2       0.0         12.0   
6050    2009-01-02    Cobar     18.4     28.9       0.0         14.8   
6052    2009-01-04    Cobar     19.4     37.6       0.0         10.8   
6053    2009-01-05    Cobar     21.9     38.4       0.0         11.4   
6054    2009-01-06    Cobar     24.2     41.0       0.0         11.2   
...            ...      ...      ...      ...       ...          ...   
142298  2017-06-20   Darwin     19.3     33.4       0.0          6.0   
142299  2017-06-21   Darwin     21.2     32.6       0.0          7.6   
142300  2017-06-22   Darwin     20.7     32.8       0.0          5.6   
142301  2017-06-23   Darwin     19.5     31.8       0.0          6.2   
142302  2017-06-24   Darwin     20.2     31.7       0.0          5.6   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
6049        12.3         SSW           48.0        ENE  ...        20.0   
6050        13.0           S           37.0        SSE  ...        30.0   
6052        10.6         NNE           46.0        NNE  ...        42.0   
6053        12.2         WNW           31.0        WNW  ...        37.0   
6054         8.4         WNW           35.0         NW  ...        19.0   
...          ...         ...            ...        ...  ...         ...   
142298      11.0         ENE           35.0         SE  ...        63.0   
142299       8.6           E           37.0         SE  ...        56.0   
142300      11.0           E           33.0          E  ...        46.0   
142301      10.6         ESE           26.0         SE  ...        62.0   
142302      10.7         ENE           30.0        ENE  ...        73.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
6049           13.0       1006.3       1004.4       2.0       5.0     26.6   
6050            8.0       1012.9       1012.1       1.0       1.0     20.3   
6052           22.0       1012.3       1009.2       1.0       6.0     28.7   
6053           22.0       1012.7       1009.1       1.0       5.0     29.1   
6054           15.0       1010.7       1007.4       1.0       6.0     33.6   
...             ...          ...          ...       ...       ...      ...   
142298         32.0       1013.9       1010.5       0.0       1.0     24.5   
142299         28.0       1014.6       1011.2       7.0       0.0     24.8   
142300         23.0       1015.3       1011.8       0.0       0.0     24.8   
142301         58.0       1014.9       1010.7       1.0       1.0     24.8   
142302         32.0       1013.9       1009.7       6.0       5.0     25.4   

        Temp3pm  RainToday  RainTomorrow  
6049       33.4         No            No  
6050       27.0         No            No  
6052       34.9         No            No  
6053       35.6         No            No  
6054       37.6         No            No  
...         ...        ...           ...  
142298     32.3         No            No  
142299     32.0         No            No  
142300     32.1         No            No  
142301     29.2         No            No  
142302     31.0         No            No  

[56420 rows x 23 columns]

In [25]:
from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder instance
label_encoder = LabelEncoder()

# Fit and transform the data
encoded_Location_data = label_encoder.fit_transform(data['Location'])
encoded_WindGustDir_data = label_encoder.fit_transform(data['WindGustDir'])
encoded_WindDir9am_data = label_encoder.fit_transform(data['WindDir9am'])
encoded_WindDir3pm_data = label_encoder.fit_transform(data['WindDir3pm'])
encoded_RainToday_data = label_encoder.fit_transform(data['RainToday'])
encoded_RainTomorrow_data = label_encoder.fit_transform(data['RainTomorrow'])

'''
# To get back the original categories
decoded_Location_data = label_encoder.inverse_transform(encoded_data)
print(f"Decoded Data: {decoded_Location_data}")
'''


'\n# To get back the original categories\ndecoded_Location_data = label_encoder.inverse_transform(encoded_data)\nprint(f"Decoded Data: {decoded_Location_data}")\n'

In [26]:
print( "Locations    : " , set( data['Location'] ) )
print( "WindGustDir  : " , set( data['WindGustDir'] ) )
print( "WindDir9am   : " , set( data['WindDir9am'] ) )
print( "WindDir3pm   : " , set( data['WindDir3pm'] ) )
print( "RainToday    : " , set( data['RainToday'] ) )
print( "RainTomorrow : " , set( data['RainTomorrow'] ) )

Locations    :  {'Hobart', 'WaggaWagga', 'Mildura', 'Woomera', 'Moree', 'Townsville', 'MountGambier', 'Darwin', 'Brisbane', 'Sale', 'Nuriootpa', 'Williamtown', 'PerthAirport', 'Melbourne', 'Canberra', 'Perth', 'Portland', 'CoffsHarbour', 'MelbourneAirport', 'Cobar', 'SydneyAirport', 'Cairns', 'AliceSprings', 'NorfolkIsland', 'Watsonia', 'Sydney'}
WindGustDir  :  {'E', 'WNW', 'ENE', 'SSE', 'NNE', 'NE', 'SW', 'SSW', 'NNW', 'ESE', 'S', 'W', 'SE', 'N', 'WSW', 'NW'}
WindDir9am   :  {'E', 'ENE', 'WNW', 'SSE', 'NNE', 'NE', 'SW', 'SSW', 'NNW', 'ESE', 'S', 'W', 'SE', 'N', 'WSW', 'NW'}
WindDir3pm   :  {'SE', 'WNW', 'ENE', 'E', 'SSE', 'NNE', 'NE', 'SSW', 'NNW', 'ESE', 'S', 'W', 'SW', 'N', 'WSW', 'NW'}
RainToday    :  {'No', 'Yes'}
RainTomorrow :  {'No', 'Yes'}


In [27]:
#field-0
print( years  )
print( months )
print( dates  )

#field( n-n )
print( encoded_Location_data    )
print( encoded_WindGustDir_data )
print( encoded_WindDir9am_data  )
print( encoded_WindDir3pm_data  )
print( encoded_RainToday_data   )
print( encoded_RainTomorrow_data) 

[2009 2009 2009 ... 2017 2017 2017]
[1 1 1 ... 6 6 6]
[ 1  2  4 ... 22 23 24]
[4 4 4 ... 6 6 6]
[11  8  5 ...  0  2  1]
[ 1 10  5 ...  0  9  1]
[12 10  6 ... 13  6  6]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           56420 non-null  object 
 1   Location       56420 non-null  object 
 2   MinTemp        56420 non-null  float64
 3   MaxTemp        56420 non-null  float64
 4   Rainfall       56420 non-null  float64
 5   Evaporation    56420 non-null  float64
 6   Sunshine       56420 non-null  float64
 7   WindGustDir    56420 non-null  object 
 8   WindGustSpeed  56420 non-null  float64
 9   WindDir9am     56420 non-null  object 
 10  WindDir3pm     56420 non-null  object 
 11  WindSpeed9am   56420 non-null  float64
 12  WindSpeed3pm   56420 non-null  float64
 13  Humidity9am    56420 non-null  float64
 14  Humidity3pm    56420 non-null  float64
 15  Pressure9am    56420 non-null  float64
 16  Pressure3pm    56420 non-null  float64
 17  Cloud9am       56420 non-null  float64
 18  Cloud3p

In [29]:


# Sample DataFrame
temp = pd.DataFrame({
 
   'year'    : years  ,
   'month'   : months ,
   'date'    : dates  ,

  'Location'     : encoded_Location_data    ,
  'WindGustDir'  : encoded_WindGustDir_data ,
  'WindDir9am'   : encoded_WindDir9am_data  ,
  'WindDir3pm'   : encoded_WindDir3pm_data  ,
  'RainToday'    : encoded_RainToday_data   ,
  'RainTomorrow' : encoded_RainTomorrow_data

})

print("Encoded DATA:")
temp

Encoded DATA:


year  month  date  Location  WindGustDir  WindDir9am  WindDir3pm  \
0      2009      1     1         4           11           1          12   
1      2009      1     2         4            8          10          10   
2      2009      1     4         4            5           5           6   
3      2009      1     5         4           14          14          15   
4      2009      1     6         4           14           7          14   
...     ...    ...   ...       ...          ...         ...         ...   
56415  2017      6    20         6            1           9           4   
56416  2017      6    21         6            0           9           9   
56417  2017      6    22         6            0           0          13   
56418  2017      6    23         6            2           9           6   
56419  2017      6    24         6            1           1           6   

       RainToday  RainTomorrow  
0              0             0  
1              0             0  
2              0             0  
3              0             0  
4              0             0  
...          ...           ...  
56415          0             0  
56416          0             0  
56417          0             0  
56418          0             0  
56419          0             0  

[56420 rows x 9 columns]

In [30]:
data.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [31]:
temp.columns

Index(['year', 'month', 'date', 'Location', 'WindGustDir', 'WindDir9am',
       'WindDir3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [32]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56420 entries, 0 to 56419
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          56420 non-null  int64
 1   month         56420 non-null  int64
 2   date          56420 non-null  int64
 3   Location      56420 non-null  int64
 4   WindGustDir   56420 non-null  int64
 5   WindDir9am    56420 non-null  int64
 6   WindDir3pm    56420 non-null  int64
 7   RainToday     56420 non-null  int64
 8   RainTomorrow  56420 non-null  int64
dtypes: int64(9)
memory usage: 3.9 MB


In [33]:
Dataset = pd.DataFrame({
 
   'year'    : years  ,
   'month'   : months ,
   'date'    : dates  ,

  'MinTemp'      : data['MinTemp']          ,
  'MaxTemp'      : data['MaxTemp']          ,
  'Rainfall'     : data['Rainfall']         ,
  'Evaporation'  : data['Evaporation']      ,
  'Sunshine'     : data['Sunshine']         , 
  'WindGustSpeed': data['WindGustSpeed']    ,
  'WindSpeed9am' : data['WindSpeed9am']     ,
  'WindSpeed3pm' : data['WindSpeed3pm']     ,
  'Humidity9am'  : data['Humidity9am']      ,
  'Humidity3pm'  : data['Humidity3pm']      ,
  'Pressure9am'  : data['Pressure9am']      ,
  'Pressure3pm'  : data['Pressure3pm']      ,
  'Cloud9am'     : data['Cloud9am']         ,
  'Cloud3pm'     : data['Cloud3pm']         ,
  'Temp9am'      : data['Temp9am']          ,
  'Temp3pm'      : data['Temp3pm']          ,
  'Location'     : encoded_Location_data    ,
  'WindGustDir'  : encoded_WindGustDir_data ,
  'WindDir9am'   : encoded_WindDir9am_data  ,
  'WindDir3pm'   : encoded_WindDir3pm_data  ,
  'RainToday'    : encoded_RainToday_data   ,
  'RainTomorrow' : encoded_RainTomorrow_data
  
})


In [34]:
len( data.columns )

23

In [35]:
len( Dataset.columns )

25

In [36]:
Dataset

year  month  date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
6049    2009      1     1     17.9     35.2       0.0         12.0      12.3   
6050    2009      1     2     18.4     28.9       0.0         14.8      13.0   
6052    2009      1     4     19.4     37.6       0.0         10.8      10.6   
6053    2009      1     5     21.9     38.4       0.0         11.4      12.2   
6054    2009      1     6     24.2     41.0       0.0         11.2       8.4   
...      ...    ...   ...      ...      ...       ...          ...       ...   
142298  2017      6    20     19.3     33.4       0.0          6.0      11.0   
142299  2017      6    21     21.2     32.6       0.0          7.6       8.6   
142300  2017      6    22     20.7     32.8       0.0          5.6      11.0   
142301  2017      6    23     19.5     31.8       0.0          6.2      10.6   
142302  2017      6    24     20.2     31.7       0.0          5.6      10.7   

        WindGustSpeed  WindSpeed9am  ...  Cloud9am  Cloud3pm  Temp9am  \
6049             48.0           6.0  ...       2.0       5.0     26.6   
6050             37.0          19.0  ...       1.0       1.0     20.3   
6052             46.0          30.0  ...       1.0       6.0     28.7   
6053             31.0           6.0  ...       1.0       5.0     29.1   
6054             35.0          17.0  ...       1.0       6.0     33.6   
...               ...           ...  ...       ...       ...      ...   
142298           35.0           9.0  ...       0.0       1.0     24.5   
142299           37.0          13.0  ...       7.0       0.0     24.8   
142300           33.0          17.0  ...       0.0       0.0     24.8   
142301           26.0           9.0  ...       1.0       1.0     24.8   
142302           30.0          15.0  ...       6.0       5.0     25.4   

        Temp3pm  Location  WindGustDir  WindDir9am  WindDir3pm  RainToday  \
6049       33.4         4           11           1          12          0   
6050       27.0         4            8          10          10          0   
6052       34.9         4            5           5           6          0   
6053       35.6         4           14          14          15          0   
6054       37.6         4           14           7          14          0   
...         ...       ...          ...         ...         ...        ...   
142298     32.3         6            1           9           4          0   
142299     32.0         6            0           9           9          0   
142300     32.1         6            0           0          13          0   
142301     29.2         6            2           9           6          0   
142302     31.0         6            1           1           6          0   

        RainTomorrow  
6049               0  
6050               0  
6052               0  
6053               0  
6054               0  
...              ...  
142298             0  
142299             0  
142300             0  
142301             0  
142302             0  

[56420 rows x 25 columns]

In [37]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   year           56420 non-null  int64  
 1   month          56420 non-null  int64  
 2   date           56420 non-null  int64  
 3   MinTemp        56420 non-null  float64
 4   MaxTemp        56420 non-null  float64
 5   Rainfall       56420 non-null  float64
 6   Evaporation    56420 non-null  float64
 7   Sunshine       56420 non-null  float64
 8   WindGustSpeed  56420 non-null  float64
 9   WindSpeed9am   56420 non-null  float64
 10  WindSpeed3pm   56420 non-null  float64
 11  Humidity9am    56420 non-null  float64
 12  Humidity3pm    56420 non-null  float64
 13  Pressure9am    56420 non-null  float64
 14  Pressure3pm    56420 non-null  float64
 15  Cloud9am       56420 non-null  float64
 16  Cloud3pm       56420 non-null  float64
 17  Temp9am        56420 non-null  float64
 18  Temp3pm

In [38]:
Dataset.describe()

year         month          date       MinTemp       MaxTemp  \
count  56420.000000  56420.000000  56420.000000  56420.000000  56420.000000   
mean    2012.221074      6.425009     15.723910     13.464770     24.219206   
std        2.450978      3.451383      8.782527      6.416689      6.970676   
min     2007.000000      1.000000      1.000000     -6.700000      4.100000   
25%     2010.000000      3.000000      8.000000      8.600000     18.700000   
50%     2012.000000      6.000000     16.000000     13.200000     23.900000   
75%     2014.000000      9.000000     23.000000     18.400000     29.700000   
max     2017.000000     12.000000     31.000000     31.400000     48.100000   

           Rainfall   Evaporation      Sunshine  WindGustSpeed  WindSpeed9am  \
count  56420.000000  56420.000000  56420.000000   56420.000000  56420.000000   
mean       2.130397      5.503135      7.735626      40.877366     15.667228   
std        7.014822      3.696282      3.758153      13.335232      8.317005   
min        0.000000      0.000000      0.000000       9.000000      2.000000   
25%        0.000000      2.800000      5.000000      31.000000      9.000000   
50%        0.000000      5.000000      8.600000      39.000000     15.000000   
75%        0.600000      7.400000     10.700000      48.000000     20.000000   
max      206.200000     81.200000     14.500000     124.000000     67.000000   

       ...      Cloud9am      Cloud3pm       Temp9am       Temp3pm  \
count  ...  56420.000000  56420.000000  56420.000000  56420.000000   
mean   ...      4.241705      4.326515     18.204961     22.710333   
std    ...      2.797162      2.647251      6.567991      6.836543   
min    ...      0.000000      0.000000     -0.700000      3.700000   
25%    ...      1.000000      2.000000     13.100000     17.400000   
50%    ...      5.000000      5.000000     17.800000     22.400000   
75%    ...      7.000000      7.000000     23.300000     27.900000   
max    ...      8.000000      9.000000     39.400000     46.100000   

           Location   WindGustDir    WindDir9am    WindDir3pm     RainToday  \
count  56420.000000  56420.000000  56420.000000  56420.000000  56420.000000   
mean      12.628837      7.485537      7.122935      7.574424      0.220879   
std        7.301231      4.792305      4.660823      4.711700      0.414843   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        7.000000      3.000000      3.000000      3.000000      0.000000   
50%       13.000000      8.000000      7.000000      8.000000      0.000000   
75%       19.000000     12.000000     11.000000     12.000000      0.000000   
max       25.000000     15.000000     15.000000     15.000000      1.000000   

       RainTomorrow  
count  56420.000000  
mean       0.220259  
std        0.414425  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 25 columns]

In [39]:
Dataset.isnull()

year  month   date  MinTemp  MaxTemp  Rainfall  Evaporation  \
6049    False  False  False    False    False     False        False   
6050    False  False  False    False    False     False        False   
6052    False  False  False    False    False     False        False   
6053    False  False  False    False    False     False        False   
6054    False  False  False    False    False     False        False   
...       ...    ...    ...      ...      ...       ...          ...   
142298  False  False  False    False    False     False        False   
142299  False  False  False    False    False     False        False   
142300  False  False  False    False    False     False        False   
142301  False  False  False    False    False     False        False   
142302  False  False  False    False    False     False        False   

        Sunshine  WindGustSpeed  WindSpeed9am  ...  Cloud9am  Cloud3pm  \
6049       False          False         False  ...     False     False   
6050       False          False         False  ...     False     False   
6052       False          False         False  ...     False     False   
6053       False          False         False  ...     False     False   
6054       False          False         False  ...     False     False   
...          ...            ...           ...  ...       ...       ...   
142298     False          False         False  ...     False     False   
142299     False          False         False  ...     False     False   
142300     False          False         False  ...     False     False   
142301     False          False         False  ...     False     False   
142302     False          False         False  ...     False     False   

        Temp9am  Temp3pm  Location  WindGustDir  WindDir9am  WindDir3pm  \
6049      False    False     False        False       False       False   
6050      False    False     False        False       False       False   
6052      False    False     False        False       False       False   
6053      False    False     False        False       False       False   
6054      False    False     False        False       False       False   
...         ...      ...       ...          ...         ...         ...   
142298    False    False     False        False       False       False   
142299    False    False     False        False       False       False   
142300    False    False     False        False       False       False   
142301    False    False     False        False       False       False   
142302    False    False     False        False       False       False   

        RainToday  RainTomorrow  
6049        False         False  
6050        False         False  
6052        False         False  
6053        False         False  
6054        False         False  
...           ...           ...  
142298      False         False  
142299      False         False  
142300      False         False  
142301      False         False  
142302      False         False  

[56420 rows x 25 columns]

In [40]:
Dataset.shape

(56420, 25)

In [41]:
Dataset.isnull().sum()

year             0
month            0
date             0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
Location         0
WindGustDir      0
WindDir9am       0
WindDir3pm       0
RainToday        0
RainTomorrow     0
dtype: int64

In [42]:
X = pd.DataFrame( Dataset.drop( 'RainTomorrow' , axis = 1 ) )

In [43]:
X

year  month  date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
6049    2009      1     1     17.9     35.2       0.0         12.0      12.3   
6050    2009      1     2     18.4     28.9       0.0         14.8      13.0   
6052    2009      1     4     19.4     37.6       0.0         10.8      10.6   
6053    2009      1     5     21.9     38.4       0.0         11.4      12.2   
6054    2009      1     6     24.2     41.0       0.0         11.2       8.4   
...      ...    ...   ...      ...      ...       ...          ...       ...   
142298  2017      6    20     19.3     33.4       0.0          6.0      11.0   
142299  2017      6    21     21.2     32.6       0.0          7.6       8.6   
142300  2017      6    22     20.7     32.8       0.0          5.6      11.0   
142301  2017      6    23     19.5     31.8       0.0          6.2      10.6   
142302  2017      6    24     20.2     31.7       0.0          5.6      10.7   

        WindGustSpeed  WindSpeed9am  ...  Pressure3pm  Cloud9am  Cloud3pm  \
6049             48.0           6.0  ...       1004.4       2.0       5.0   
6050             37.0          19.0  ...       1012.1       1.0       1.0   
6052             46.0          30.0  ...       1009.2       1.0       6.0   
6053             31.0           6.0  ...       1009.1       1.0       5.0   
6054             35.0          17.0  ...       1007.4       1.0       6.0   
...               ...           ...  ...          ...       ...       ...   
142298           35.0           9.0  ...       1010.5       0.0       1.0   
142299           37.0          13.0  ...       1011.2       7.0       0.0   
142300           33.0          17.0  ...       1011.8       0.0       0.0   
142301           26.0           9.0  ...       1010.7       1.0       1.0   
142302           30.0          15.0  ...       1009.7       6.0       5.0   

        Temp9am  Temp3pm  Location  WindGustDir  WindDir9am  WindDir3pm  \
6049       26.6     33.4         4           11           1          12   
6050       20.3     27.0         4            8          10          10   
6052       28.7     34.9         4            5           5           6   
6053       29.1     35.6         4           14          14          15   
6054       33.6     37.6         4           14           7          14   
...         ...      ...       ...          ...         ...         ...   
142298     24.5     32.3         6            1           9           4   
142299     24.8     32.0         6            0           9           9   
142300     24.8     32.1         6            0           0          13   
142301     24.8     29.2         6            2           9           6   
142302     25.4     31.0         6            1           1           6   

        RainToday  
6049            0  
6050            0  
6052            0  
6053            0  
6054            0  
...           ...  
142298          0  
142299          0  
142300          0  
142301          0  
142302          0  

[56420 rows x 24 columns]

In [44]:
y = pd.DataFrame( Dataset['RainTomorrow'] )

In [45]:
y

RainTomorrow
6049               0
6050               0
6052               0
6053               0
6054               0
...              ...
142298             0
142299             0
142300             0
142301             0
142302             0

[56420 rows x 1 columns]

In [46]:
from sklearn.model_selection import train_test_split

# Perform the train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,  stratify = y  , random_state=2)

# Check the results
print("X_train:\n", X_train)
#print("X_test:\n", X_test)
print("y_train:\n", y_train)
#print("y_test:\n", y_test)

X_train:
         year  month  date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
94760   2013      3    19     23.0     32.8       0.0          8.0       9.3   
88524   2012      8    16     17.3     27.2       0.0          3.8       5.7   
121749  2011      8    16     11.5     17.7       7.8          4.6       8.3   
64450   2009      9    17     15.2     17.7       0.0          8.4       0.0   
35706   2015      3    26     17.9     29.2       0.0          5.8      10.4   
...      ...    ...   ...      ...      ...       ...          ...       ...   
80472   2016      1    17     12.8     32.7       0.0          8.6      11.5   
75814   2011      5    15      9.6     13.8       0.8          0.8       1.2   
66568   2015     10     3     16.7     31.0       0.0         11.0       9.8   
120074  2015     12    10     13.9     27.8       0.0          8.0      13.1   
71229   2011      5    17      0.0     16.3       0.0          1.8       9.1   

        WindGustSpeed  WindSp

In [47]:
print( X_train.shape )
print( y_train.shape )

(39494, 24)
(39494, 1)


In [48]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = SVC(kernel='linear')  # You can choose 'linear', 'poly', 'rbf', etc.
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

print("Classification Report:")
print(classification_report(y_test, y_pred))


/home/abinesh/py-run/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.86
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.95      0.91     13198
           1       0.75      0.52      0.62      3728

    accuracy                           0.86     16926
   macro avg       0.81      0.74      0.76     16926
weighted avg       0.85      0.86      0.85     16926



In [50]:
y_pred

array([0, 0, 1, ..., 0, 1, 0])

In [51]:
X_test

year  month  date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
80560   2016      4    14      9.0     27.3       0.0          2.4       6.3   
61554   2010      1     8      9.3     36.4       0.0          6.6      11.1   
101491  2014      7    30     11.6     15.8       0.6          1.0       3.1   
9288    2009      8    19      6.6     19.3       0.0          2.8      10.5   
65406   2012      5    30      5.5     13.9       0.0          0.8       0.0   
...      ...    ...   ...      ...      ...       ...          ...       ...   
104485  2014      7    15      4.9     11.6       0.6          0.0       0.8   
140646  2012     10    13     23.5     36.6       0.0          9.0      11.1   
62991   2014      3    14     10.6     26.4       0.0          4.6       9.6   
86258   2014     11    27     23.4     32.0       3.0          6.8      10.4   
9642    2010      8     8      4.1     17.2       0.0          3.2      10.3   

        WindGustSpeed  WindSpeed9am  ...  Pressure3pm  Cloud9am  Cloud3pm  \
80560            35.0           7.0  ...       1022.6       6.0       7.0   
61554            37.0           9.0  ...       1012.8       2.0       7.0   
101491           69.0          31.0  ...       1008.6       7.0       7.0   
9288             26.0          17.0  ...       1023.9       1.0       1.0   
65406            17.0           9.0  ...       1034.3       7.0       7.0   
...               ...           ...  ...          ...       ...       ...   
104485           39.0          15.0  ...       1009.4       8.0       7.0   
140646           41.0          13.0  ...       1009.9       2.0       1.0   
62991            41.0           7.0  ...       1011.4       5.0       3.0   
86258            83.0           6.0  ...       1012.1       6.0       1.0   
9642             20.0           7.0  ...       1018.8       1.0       0.0   

        Temp9am  Temp3pm  Location  WindGustDir  WindDir9am  WindDir3pm  \
80560      14.5     26.8        23            6           2           6   
61554      18.6     33.2        18            0           4           1   
101491     13.6     15.2        12            7           7           7   
9288       16.8     19.1         5           15          12           0   
65406      11.0     13.3         9            9          15          11   
...         ...      ...       ...          ...         ...         ...   
104485      7.6     11.4        14           14           6           6   
140646     29.1     34.3         6            5           2           5   
62991      14.4     25.4        18            0          14           0   
86258      28.7     30.1         1           12           6           4   
9642       14.4     17.1         5           15          15           9   

        RainToday  
80560           0  
61554           0  
101491          0  
9288            0  
65406           0  
...           ...  
104485          0  
140646          0  
62991           0  
86258           1  
9642            0  

[16926 rows x 24 columns]

In [150]:

index = int( input("Enter The Index : "))

result = Dataset.iloc[index]
print( list(result ))

test  = Dataset.drop("RainTomorrow" , axis = 1 ).iloc[index]
print( list( test ) )

test = scaler.transform( np.array( test ).reshape(1,-1) )
print( test )

testout = model.predict( test )
print( testout )

if( testout[0] == 1 ) :
    print("RainTomorrow : 1 ")
else :
    print("RainTomorrow : 0 ")

Enter The Index :  96


[2009.0, 4.0, 10.0, 16.5, 20.6, 14.4, 6.0, 0.0, 30.0, 7.0, 9.0, 97.0, 76.0, 1021.3, 1019.3, 7.0, 7.0, 16.9, 19.9, 4.0, 0.0, 4.0, 5.0, 1.0, 1.0]
[2009.0, 4.0, 10.0, 16.5, 20.6, 14.4, 6.0, 0.0, 30.0, 7.0, 9.0, 97.0, 76.0, 1021.3, 1019.3, 7.0, 7.0, 16.9, 19.9, 4.0, 0.0, 4.0, 5.0, 1.0]
[[-1.31291146 -0.70322688 -0.64717602  0.47736655 -0.51589989  1.74096615
   0.13432051 -2.06444131 -0.81894488 -1.04483347 -1.27017723  1.68416281
   1.31228359  0.58431383  0.65280273  0.9889131   1.00782215 -0.19368875
  -0.40807681 -1.1806386  -1.55337652 -0.66771756 -0.5452682   1.88317116]]
[1]
RainTomorrow : 1 


/home/abinesh/py-run/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [142]:
rt = list( Dataset['RainTomorrow'] ) 

for i in range( len( rt )) :
    if( rt[i] == 1 ) :
        print(i)

17
20
21
32
42
43
45
46
52
69
70
95
96
97
132
133
139
144
145
146
149
163
168
169
185
190
194
242
279
307
310
330
337
338
339
344
345
349
378
379
381
382
385
402
403
404
427
428
434
435
436
451
460
476
477
480
481
483
497
498
505
511
522
535
541
542
549
550
558
559
560
565
575
576
577
578
579
581
584
585
589
591
596
597
598
601
603
609
614
616
617
618
619
620
621
622
623
624
625
627
628
629
633
634
635
636
637
648
649
650
651
655
661
662
663
664
665
666
670
672
674
675
676
681
683
684
685
686
700
701
702
703
716
756
759
773
783
784
785
790
798
799
805
807
820
823
824
827
832
836
837
845
847
848
849
853
866
877
879
880
881
882
883
884
885
886
887
893
896
897
898
901
902
903
904
907
908
909
910
911
913
916
917
918
919
922
937
940
952
953
954
955
956
961
969
970
983
984
987
988
991
992
993
994
997
998
999
1000
1009
1010
1017
1018
1019
1022
1028
1031
1033
1034
1035
1045
1050
1051
1052
1053
1054
1057
1064
1065
1074
1086
1087
1092
1102
1103
1110
1113
1114
1115
1116
1117
1118
1119
1120
1124
1